import os
from os import system, name
from time import sleep  
os.system('cls')   
print ("************                         ")
sleep(2)
os.system('cls')
print("")
print ("                      ***************")
print (" ")
sleep(2)
os.system('cls')
print ("************                         ")
print ("             Hello World!!! ")
print ("                      ***************")
sleep(2)
os.system('cls')
print ("H")
print ("E")
print ("L")
print ("L")
print ("O")
print ()
sleep(2)
print ("W")
print ("O")
print ("R")
print ("L")
print ("D")
sleep(2)
os.system('cls')
print ("     HELLO")
print ("           WORLD!!")
exit(0)
